[compat]
CSV = "^0.10"
DataFrames = "^1.6"
DataFramesMeta = "^0.15.6"
Distributions = "^0.25.122" # <--- CONFLICT
InlineStrings = "^1.4.5"
JLD2 = "^0.6.2"
JSON3 = "^1.14.3"
LinearAlgebra = "^1.11.0"
Memoization = "^0.2.2"
Optimization = "^4.8.0"
OptimizationOptimJL = "^0.4.5"
Parsers = "^2.8.3"
ProgressMeter = "^1.11.0"
ReverseDiff = "^1.16.1"
Revise = "^3.10.0"
Statistics = "^1.11.1"
StatsPlots = "^0.15.8"
Turing = "^0.40.4"         # <--- CONFLICT
julia = "^1.9"
