# current_development/MetaModels/r09_advanced_staking_runner.jl
#
# ===========================================================================
# ADVANCED STAKING RUNNER: DUAL-ODDS WORKFLOW
# ===========================================================================
# This runner implements the "Anchor vs Staking" architectural split:
# 
# 1. SHARP ANCHOR (Meta Model Training):
#    We train the Meta Model on the sharpest available market prices 
#    (e.g., Betfair 10 minutes before kickoff). This ensures the Meta Model 
#    learns true structural divergence against a highly efficient benchmark, 
#    resulting in the cleanest separation of "Good" vs "Bad" regimes.
#
# 2. LOOSE STAKING (Kelly & PnL Evaluation):
#    Instead of placing our simulated bets at the hyper-efficient sharp price, 
#    we evaluate our Kelly stakes against an earlier, looser market 
#    (e.g., Betfair 60 to 20 minutes out, or Sofascore/Bet365).
#    This allows us to capture the early value/drift while perfectly maintaining 
#    the strict regime gate generated by the sharp anchor.
# ===========================================================================

using Pkg; Pkg.activate(".")
using BayesianFootball
using DataFrames
using Dates
using Serialization
using ThreadPinning

# Lock OS threads for MCMC efficiency
pinthreads(:cores)

println("===========================================================================")
println("  INITIALIZING DUAL-ODDS META MODEL WORKFLOW")
println("===========================================================================")

# ===========================================================================
# 1. LOAD LAYER 1 RESULTS
# ===========================================================================
save_dir = "./data/meta_model_layer1/ireland/"
saved_files = BayesianFootball.Experiments.list_experiments(save_dir, data_dir="")
exp_results = BayesianFootball.Experiments.load_experiment(saved_files, 1)

println("    Loaded L1 Model: $(typeof(exp_results.task.model))")

# ===========================================================================
# 2. LOAD DATASTORE & GENERATE DUAL ODDS
# ===========================================================================
println("\n[2] Loading Base DataStore...")
ds_raw = BayesianFootball.Data.load_datastore_cached(BayesianFootball.Data.Ireland())

println("\n    -> Computing SHARP Anchor Odds (-10 to 0 mins)...")
betfair_sharp = BayesianFootball.Data.summarize_betfair_market(
    ds_raw, 
    open_window=(-100000.0, -10.0), 
    close_window=(-10.0, 0.0)
)

# The Meta Model Datastore MUST contain the Sharp Odds
ds = BayesianFootball.Data.DataStore(
    ds_raw.segment, ds_raw.matches, ds_raw.statistics,
    betfair_sharp, 
    ds_raw.lineups, ds_raw.incidents, ds_raw.betfair_odds
)

println("    -> Computing LOOSE Staking Odds (-60 to -20 mins)...")
betfair_loose = BayesianFootball.Data.summarize_betfair_market(
    ds_raw, 
    open_window=(-100000.0, -60.0), 
    close_window=(-60.0, -20.0)
)

# NOTE: To bet against the bookmaker instead of the exchange, simply swap:
# loose_staking_odds = ds_raw.odds
loose_staking_odds = betfair_loose 

# ===========================================================================
# 3. CONFIGURE META MODEL
# ===========================================================================
println("\n[3] Configuring Meta Model and Sampler...")
using .MetaModels

meta_model = MetaModels.ConvexMixtureMetaModel(
    dynamics_config  = MetaModels.MetaGRWDynamicsConfig(σ_prior=0.2),
    hierarchy_config = MetaModels.GlobalMetaHierarchyConfig() 
)


sampler_config = BayesianFootball.Samplers.QueuedNUTSConfig(
    n_samples = 500,
    n_chains  = 2,
    n_warmup  = 200,
    accept_rate = 0.65,
    max_depth   = 10,
    initialisation = BayesianFootball.Samplers.UniformInit(-2, 2),
)


# ===========================================================================
# 4. RUN MULTI-MARKET EXPERIMENTS
# ===========================================================================
TARGET_SELECTIONS = [:under_25, :over_25]
min_edge = 0.00

println("\n[4] Running Advanced Meta Workflow across $(length(TARGET_SELECTIONS)) markets...")
multi_market_results, multi_market_ledgers = MetaModels.run_multi_market_experiments(
    TARGET_SELECTIONS,
    exp_results,
    meta_model,
    sampler_config,
    ds;
    min_edge=min_edge,
    staking_odds=loose_staking_odds  # <--- Evaluates Kelly against the loose odds
)

# ===========================================================================
# 5. PERSIST RESULTS TO DISK
# ===========================================================================
save_dir = "./current_development/save_dir_meta_advanced"
mkpath(save_dir)
println("\n[5] Serializing dual-odds multi-market results to disk...")
serialize(joinpath(save_dir, "multi_market_results.jls"), multi_market_results)
serialize(joinpath(save_dir, "multi_market_ledgers.jls"), multi_market_ledgers)
println("    Successfully saved to: $save_dir")

# ===========================================================================
# 6. STREAMLINED REPORTING
# ===========================================================================
println("\n" * "="^75)
println("  GENERATING CONSOLIDATED HURDLE REPORTS")
println("="^75)

markets_evaluated = collect(keys(multi_market_ledgers))
final_metrics = MetaModels.evaluate_multiple_markets(multi_market_ledgers, markets_evaluated; min_edge=min_edge)

println("\nRunner finished successfully.")
